// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NumberRepository is an autogenerated mock type for the NumberRepository type
type NumberRepository struct {
	mock.Mock
}

// GetN1 provides a mock function with given fields:
func (_m *NumberRepository) GetN1() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetN2 provides a mock function with given fields:
func (_m *NumberRepository) GetN2() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewNumberRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewNumberRepository creates a new instance of NumberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNumberRepository(t mockConstructorTestingTNewNumberRepository) *NumberRepository {
	mock := &NumberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
